DROP TABLE IF EXISTS `t_user_role`;
DROP TABLE IF EXISTS `t_role`;
DROP TABLE IF EXISTS `t_user`;

CREATE TABLE t_user (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL ,
  email VARCHAR(64) NOT NULL UNIQUE ,
  phone VARCHAR(32)
) ENGINE = INNODB DEFAULT CHARSET=utf8;

CREATE TABLE t_role (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(16) NOT NULL UNIQUE
) ENGINE = INNODB DEFAULT CHARSET=utf8;

CREATE TABLE t_user_role (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL ,
  role_id INT NOT NULL ,
  CONSTRAINT `ref_user_id` FOREIGN KEY (`user_id`) REFERENCES `t_user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE ,
  CONSTRAINT `ref_role_id` FOREIGN KEY (`role_id`) REFERENCES `t_role`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE KEY (`user_id`, `role_id`)
) ENGINE = INNODB DEFAULT CHARSET=utf8;
