DROP TABLE IF EXISTS `t_user`;
CREATE TABLE t_user (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL ,
  email VARCHAR(64) NOT NULL UNIQUE ,
  phone VARCHAR(32)
) ENGINE = INNODB DEFAULT CHARSET=utf8;
